# AeroSpace is an i3-like tiling window manager for macOS
cask "nikitabobko/tap/aerospace"
# JankyBorders is a lightweight window border system for macOS
cask "felixkratz/formulae"
# trust "felixkratz/formulae"
brew "borders"
# brew services start borders
