# Distributed revision control system
brew "git"
# Small git utilities
brew "git-extras"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Simple terminal UI for git commands
brew "lazygit"
# GIT elient
cask "fork"
