# Display time
SPACESHIP_TIME_SHOW=false

# Display username always
SPACESHIP_USER_SHOW=always

# Do not truncate path in repos
SPACESHIP_DIR_TRUNC_REPO=false

# Adds sections to the prompt
# https://spaceship-prompt.sh/config/prompt/
# spaceship add git
# spaceship add package
# spaceship add node
# spaceship add ruby
# spaceship add aws
# spaceship add docker

# icons
SPACESHIP_AWS_SYMBOL=" "
SPACESHIP_CHAR_SYMBOL=" "
SPACESHIP_DOCKER_SYMBOL=" "
SPACESHIP_NODE_SYMBOL=" "
SPACESHIP_PACKAGE_SYMBOL=" "
SPACESHIP_ELIXIR_SYMBOL=" "
SPACESHIP_PYTHON_SYMBOL=" "
SPACESHIP_RUBY_SYMBOL=" "
SPACESHIP_RUST_SYMBOL=" "
SPACESHIP_LUA_SYMBOL=" "
SPACESHIP_GIT_SYMBOL=" "
# SPACESHIP_PROMPT_DEFAULT_SUFFIX="  "
# SPACESHIP_GIT_STATUS_SUFFIX="  "
# SPACESHIP_GIT_STATUS_PREFIX=" " # hide icon
# SPACESHIP_GIT_STATUS_SUFFIX="${SPACESHIP_PROMPT_DEFAULT_SUFFIX}" # hide icon
# SPACESHIP_GIT_STATUS_COLOR="red"
# SPACESHIP_GIT_STATUS_UNTRACKED="? "
# SPACESHIP_GIT_STATUS_ADDED=" "
# SPACESHIP_GIT_STATUS_MODIFIED=" "
# SPACESHIP_GIT_STATUS_RENAMED=" "
# SPACESHIP_GIT_STATUS_DELETED=" "
# SPACESHIP_GIT_STATUS_STASHED=" "
# SPACESHIP_GIT_STATUS_UNMERGED="ﱵ "
# SPACESHIP_GIT_STATUS_AHEAD=" "
# SPACESHIP_GIT_STATUS_BEHIND=" "
# SPACESHIP_GIT_STATUS_DIVERGED=" "
