tap "homebrew/cask-fonts"
# Secure runtime for JavaScript and TypeScript
brew "deno"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Command-line fuzzy finder written in Go
brew "fzf"
# Distributed revision control system
brew "git"
# Language Server for the Lua language
brew "lua-language-server"
# Package manager for the Lua programming language
brew "luarocks"
# Parser generator tool and incremental parsing library
brew "tree-sitter"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Extremely fast tool to remove dupes and other lint from your filesystem
brew "rmlint"
# Developer targeted fonts with a high number of glyphs
cask "font-jetbrains-mono-nerd-font"
