tap "jesseduffield/lazydocker"
# A simple terminal UI for docker, written in Go
brew "jesseduffield/lazydocker/lazydocker"
# App to build and share containerized applications and microservices
cask "docker"
# Isolated development environments using Docker
brew "docker-compose"
