return {
  -- documentFeatures = {
  --   documentColor = false,
  --   documentFormatting = {
  --     defaultPrintWidth = 80,
  --   },
  --   documentSymbol = true,
  --   foldingRange = true,
  --   linkedEditingRange = true,
  --   selectionRange = true,
  -- },
  -- languageFeatures = {
  --   callHierarchy = true,
  --   codeAction = true,
  --   codeLens = true,
  --   completion = {
  --     defaultAttrNameCase = 'kebabCase',
  --     defaultTagNameCase = 'both',
  --   },
  --   definition = true,
  --   diagnostics = true,
  --   documentHighlight = true,
  --   documentLink = true,
  --   hover = true,
  --   implementation = true,
  --   references = true,
  --   rename = true,
  --   renameFileRefactoring = true,
  --   schemaRequestService = true,
  --   semanticTokens = false,
  --   signatureHelp = true,
  --   typeDefinition = true,
  -- },
  -- typescript = {
  --   serverPath = '/usr/local/lib/node_modules/typescript/lib/ja/diagnosticMessages.generated.json',
  -- }
}
