# Extendable version manager with support for Ruby, Node.js, Erlang & more
brew "asdf"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Distributed revision control system
brew "git"
