# see: https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/yarn/yarn.plugin.zsh
alias pn="pnpm"

alias pni="pnpm install"
alias pnid="pnpm add --dev"
alias pnb="pnpm build"
alias pnbd="pnpm build:dev"
alias pncc="pnpm cache clean"
alias pnd="pnpm dev"
alias pnf="pnpm format"
alias pnln="pnpm lint"
alias pnlnf="pnpm lint --fix"

alias pns="pnpm serve"
alias pnsd="pnpm serve:docs"
alias pnst="pnpm start"
alias pnt="pnpm test"
alias pntw="pnpm test:watch"
alias pnui="pnpm update --interactive"
alias pnuil="pnpm update --interactive --latest"
