# see: https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/yarn/yarn.plugin.zsh
alias y="yarn"

alias ya="yarn add"
alias yad="yarn add --dev"
alias yap="yarn add --peer"
alias yb="yarn build"
alias ybd="yarn build:dev"
alias ycc="yarn cache clean"
alias yd="yarn dev"
alias yf="yarn format"
alias yln="yarn lint"
alias ylnf="yarn lint --fix"
alias yls="yarn list"
alias yrm="yarn remove"
alias ys="yarn serve"
alias ysd="yarn serve:docs"
alias yst="yarn start"
alias yt="yarn test"
alias ytc="yarn test --coverage"
alias ytw="yarn test:watch"
alias yuc="yarn global upgrade && yarn cache clean"
alias yui="yarn upgrade-interactive"
alias yuil="yarn upgrade-interactive --latest"
alias yup="yarn upgrade"
# --- global
alias yga="yarn global add"
alias ygls="yarn global list"
alias ygrm="yarn global remove"
alias ygu="yarn global upgrade"
