tap "homebrew/cask-versions"
tap "homebrew/cask-fonts"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2-beta"
# Developer targeted fonts with a high number of glyphs
cask "font-fira-code-nerd-font"
